[project]
name = "hearts-renderer-cli"
version = "0.0.0"
description = "Hearts CLI renderer"
requires-python = ">=3.13"
dependencies = ["hearts-engine"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/hearts_renderer_cli"]
